
const APP = {
	CREATE_EXERCISE : "APP_CREATE_EXERCISE",
	REMOVE_EXERCISE : "APP_REMOVE_EXERCISE",
	CREATE_WORKOUT : "APP_CREATE_WORKOUT",
	REMOVE_WORKOUT : "APP_REMOVE_WORKOUT"
};

export const ActionTypes = {
	APP: APP
};